package org.nag.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscribe.proto

public interface SubscribeRespProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscribeRespProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 subReqID = 1;</code>
   * @return The subReqID.
   */
  int getSubReqID();

  /**
   * <code>int32 respCode = 2;</code>
   * @return The respCode.
   */
  int getRespCode();

  /**
   * <code>string desc = 3;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 3;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
