package org.nag.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscribe.proto

public final class Subscribe {
  private Subscribe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeReqProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeReqProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeRespProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeRespProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Subscribe.proto\"r\n\021SubscribeReqProto\022\020" +
      "\n\010subReqID\030\001 \001(\005\022\020\n\010userName\030\002 \001(\t\022\023\n\013pr" +
      "oductName\030\003 \001(\t\022\023\n\013phoneNumber\030\004 \001(\t\022\017\n\007" +
      "address\030\005 \003(\t\"F\n\022SubscribeRespProto\022\020\n\010s" +
      "ubReqID\030\001 \001(\005\022\020\n\010respCode\030\002 \001(\005\022\014\n\004desc\030" +
      "\003 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SubscribeReqProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubscribeReqProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeReqProto_descriptor,
        new java.lang.String[] { "SubReqID", "UserName", "ProductName", "PhoneNumber", "Address", });
    internal_static_SubscribeRespProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SubscribeRespProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeRespProto_descriptor,
        new java.lang.String[] { "SubReqID", "RespCode", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
